### ISSUE TITLE
CocoaPods could not find compatible versions for pod "screen_time_api_ios"

### ISSUE THREAD

**Issue by yungukbae** [kboy-silvergym/screen_time_api_ios#2]
Hello, I have some installation issues when installing CocoaPods.
Below is an error log when running 'flutter run'

```Automatically signing iOS for device deployment using specified development team in Xcode project: GUPF66FP6B
Running pod install...                                             510ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `screen_time_api_ios` from `.symlinks/plugins/screen_time_api_ios/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "screen_time_api_ios":
      In Podfile:
        screen_time_api_ios (from `.symlinks/plugins/screen_time_api_ios/ios`)

    Specs satisfying the `screen_time_api_ios (from `.symlinks/plugins/screen_time_api_ios/ios`)` dependency were found, but they required a higher
    minimum deployment target.

    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in
    resolve_dependencies'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1080:in
    `resolve_dependencies'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
    /Users/baeyungug/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
    /Users/baeyungug/.rbenv/versions/3.2.2/bin/pod:25:in `load'
    /Users/baeyungug/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `11.0` on target `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Exception: Error running pod install```

**Comment by yungukbae** [comment]
I reslove this issue by change ios build version to 15.0.
